#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include "err_handler.h"
#include "instr.h"
#include "instr_pipeline.h"
#include "forward.h"
#include "machine.h"
#include "hw_elts.h"

#define SP_NUM 31
#define XZR_NUM 32

extern machine_t guest;
extern mem_status_t dmem_status;

extern int64_t W_wval;
d_ctl_sigs_t *d_sigs;

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally. 
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */

static comb_logic_t 
generate_DXMW_control(opcode_t op,
                      d_ctl_sigs_t *D_sigs, x_ctl_sigs_t *X_sigs, m_ctl_sigs_t *M_sigs, w_ctl_sigs_t *W_sigs) {
    //d_sigs = D_sigs;
    D_sigs->src2_sel = (op == OP_STUR);
    X_sigs->set_CC = (op == OP_ADDS_RR || op == OP_CMP_RR || op == OP_TST_RR);
    X_sigs->valb_sel = (op == OP_ADDS_RR || op == OP_CMP_RR || op == OP_MVN || op == OP_ORR_RR || op == OP_EOR_RR || op == OP_TST_RR || op == OP_CSEL || op == OP_CSINC || op == OP_CSINV || op == OP_CSNEG); //only rr format has 2nd val as register
    M_sigs->dmem_read = (op == OP_LDUR);
    M_sigs->dmem_write = (op == OP_STUR);
    W_sigs->dst_sel = (op == OP_BL || op == OP_BLR);
    W_sigs->w_enable = !(op == OP_STUR || op == OP_B || op == OP_B_COND || op == OP_RET || op == OP_HLT || op == OP_NOP || op == OP_ERROR || op == OP_CBNZ || op == OP_CBZ || op == OP_BR);
    W_sigs->wval_sel = (op == OP_LDUR);
    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */

static comb_logic_t 
extract_immval(uint32_t insnbits, opcode_t op, int64_t *imm) {
    switch (op)
    {
    case OP_LDUR:
        *imm = bitfield_s64(insnbits, 12, 9);
        break;
    case OP_STUR:
        *imm = bitfield_s64(insnbits, 12, 9);
        break;
    case OP_MOVK:
        *imm = bitfield_u32(insnbits, 5, 16);
        break;
    case OP_MOVZ:
        *imm = bitfield_u32(insnbits, 5, 16);
        break;
    case OP_ADRP:
        *imm = ((bitfield_u32(insnbits, 5, 19) << 2) + bitfield_u32(insnbits, 29, 2)) << 12;
        break;
    case OP_ADD_RI:
        *imm = bitfield_u32(insnbits, 10, 12);
        break;
    case OP_SUB_RI:
        *imm = bitfield_u32(insnbits, 10, 12);
        break;
    case OP_LSL:
        *imm = 32 - bitfield_u32(insnbits, 16, 5);
        break;
    case OP_LSR:
        *imm = bitfield_u32(insnbits, 16, 5);
        break;
    case OP_ASR:
        *imm = 32 - bitfield_u32(insnbits, 16, 5);
        break;
    case OP_B:
        *imm = bitfield_s64(insnbits, 0, 26);
        break;
    case OP_B_COND:
        *imm = bitfield_s64(insnbits, 5, 19);
        break;
    case OP_BL:
        *imm = bitfield_s64(insnbits, 0, 26);
        break;
    case OP_CBZ:
        *imm = bitfield_s64(insnbits, 5, 19);
        break;
    case OP_CBNZ:
        *imm = bitfield_s64(insnbits, 5, 19);
        break;
    default:
        //no imm in other cases
        *imm = 0;
        break;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t
decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    switch (op)
    {
    case OP_ADD_RI:
    case OP_ADDS_RR:
    case OP_LDUR:
    case OP_STUR:
    case OP_ADRP:
        *ALU_op = PLUS_OP;
        break;
    case OP_SUB_RI:
    case OP_SUBS_RR:
    case OP_CMP_RR:
        *ALU_op = MINUS_OP;
        break;
    case OP_MVN:
        *ALU_op = INV_OP;
        break;
    case OP_ORR_RR:
        *ALU_op = OR_OP;
        break;
    case OP_EOR_RR:
        *ALU_op = EOR_OP;
        break;
    case OP_ANDS_RR:
    case OP_TST_RR:
        *ALU_op = AND_OP;
        break;
    case OP_MOVK:
    case OP_MOVZ:
        *ALU_op = MOV_OP;
        break;
    case OP_LSL:
        *ALU_op = LSL_OP;
        break;
    case OP_LSR:
        *ALU_op = LSR_OP;
        break;
    case OP_ASR:
        *ALU_op = ASR_OP;
        break;
    case OP_CSEL:
        *ALU_op = CSEL_OP;
        break;
    case OP_CSINC:
        *ALU_op = CSINC_OP;
        break;
    case OP_CSINV:
        *ALU_op = CSINV_OP;
        break;
    case OP_CSNEG:
        *ALU_op = CSNEG_OP;
        break;
    case OP_CBZ:
        *ALU_op = CBZ_OP;
        break;
    case OP_CBNZ:
        *ALU_op = CBNZ_OP;
        break;
    default:
        *ALU_op = PASS_A_OP;
        break;
    }
    return;
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */

comb_logic_t 
copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    dest->dmem_read = src->dmem_read;
    dest->dmem_write = src->dmem_write;
    return;
}

comb_logic_t 
copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    dest->dst_sel = src->dst_sel;
    dest->w_enable = src->w_enable;
    dest->wval_sel = src->wval_sel;
    return;
}

comb_logic_t
extract_regs(uint32_t insnbits, opcode_t op, 
             uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    if (op == OP_LDUR || op == OP_STUR) {
        //M
        *src1 = bitfield_u32(insnbits, 5, 5);
        *dst = bitfield_u32(insnbits, 0, 5);
        *src2 = bitfield_u32(insnbits, 0, 5);
    } else if (op == OP_MOVK || op == OP_MOVZ) {
        //I1
        if (op == OP_MOVZ) {
            *src1 = 33;
            *src2 = 33;
        } else {
            *src1 = bitfield_u32(insnbits, 0, 5);
            *src2 = 33;
        }
        
        *dst = bitfield_u32(insnbits, 0, 5);
    } else if (op == OP_ADRP) {
        //I2
        *dst = bitfield_u32(insnbits, 0, 5);
    } else if (op == OP_ADD_RI || op == OP_SUB_RI || op == OP_LSL || op == OP_LSR || op == OP_ASR) {
        //RI
        *src1 = bitfield_u32(insnbits, 5, 5);
        *src2 = 33;
        *dst = bitfield_u32(insnbits, 0, 5);
    } else if (op == OP_ADDS_RR || op == OP_CMP_RR || op == OP_MVN || op == OP_ORR_RR || op == OP_EOR_RR || op == OP_TST_RR) {
        //RR
        *src1 = bitfield_u32(insnbits, 5, 5);
        *src2 = bitfield_u32(insnbits, 16, 5);
        *dst = bitfield_u32(insnbits, 0, 5);
    } else if (op == OP_RET) {
        *src1 = bitfield_u32(insnbits, 5, 5);
    } else if (op == OP_CSEL || op == OP_CSINC || op == OP_CSINV || op == OP_CSNEG) {
        //EC CSxxx stuff
        *src1 = bitfield_u32(insnbits, 5, 5);
        *src2 = bitfield_u32(insnbits, 16, 5);
        *dst = bitfield_u32(insnbits, 0, 5);
    } else if (op == OP_CBZ || op == OP_CBNZ) {
        //EC CB(N)Z
        *src1 = bitfield_u32(insnbits, 0, 5);
    } else if (op == OP_BR || op == OP_BLR) {
        //EC B(L)R
        *src1 = bitfield_u32(insnbits, 5, 5);
    }
    //exceptions
    //insbits having 11111 in bits we use for src1, src2, and src3 means we need to figure out if it is xzr or sp
    if (*src1 == 0b11111) {
        if (op == OP_LDUR || op == OP_STUR || op == OP_ADD_RI || op == OP_SUB_RI) {
            *src1 = SP_NUM;
        } else {
            *src1 = XZR_NUM;
        }
    }
    if (*src2 == 0b11111) {
        *src2 = XZR_NUM + 1;
    }
    if (*dst == 0b11111) {
        if (op == OP_ADD_RI || op == OP_SUB_RI) {
            *dst = SP_NUM;
        } else {
            *dst = XZR_NUM;
        }
    }
    return;
}

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 * 
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 * Additionally, make sure the register file is updated
 * with W_out's output when you call it in this stage.
 * 
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval,
 * and decide_alu_op.
 */

comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {
    
    generate_DXMW_control(in->op, &d_sigs, &out->X_sigs, &out->M_sigs, &out->W_sigs);
    uint8_t src1;
    uint8_t src2;
    extract_regs(in->insnbits, in->op, &src1, &src2, &out->dst);
    extract_immval(in->insnbits, in->op, &out->val_imm);
    decide_alu_op(in->op, &out->ALU_op);
    regfile(src1, src2, W_out->dst, W_wval, W_out->W_sigs.w_enable, &out->val_a, &out->val_b);
    out->op = in->op;
    out->print_op = in->print_op; 
    forward_reg(src1, src2, X_out->dst, M_out->dst, W_out->dst, M_in->val_ex, M_out->val_ex, 
        W_in->val_mem, W_out->val_ex, W_out->val_mem, M_out->W_sigs.wval_sel, W_out->W_sigs.wval_sel, 
        X_out->W_sigs.w_enable, M_out->W_sigs.w_enable, W_out->W_sigs.w_enable, &out->val_a, &out->val_b);

    if (in->op == OP_BL) {
        out->dst = 30;
    }

        out->seq_succ_PC = in->seq_succ_PC;
    //do adrp 
    if (in->op == OP_ADRP) {
        out->val_a = in->adrp_val;
    }
    //do cond
    if (in->op == OP_B_COND) {
        out->cond = bitfield_u32(in->insnbits, 0, 4);
    } else if (in->op == OP_CSEL || in->op == OP_CSINC || in->op == OP_CSINV || in->op == OP_CSNEG) {
        out->cond = bitfield_u32(in->insnbits, 12, 4);
    }
    //do hw
    if (in->op == OP_MOVK || in->op == OP_MOVZ) {
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) * 16;
    } else {
        out->val_hw = 0;
    }
    //write to registers as requested by writeback
    out->status = in->status;
    return;
}